# Generated by Django 6.0.1 on 2026-02-04 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_date_created_deck_created_at_alter_deck_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('W', 'White'), ('U', 'Blue'), ('B', 'Black'), ('R', 'Red'), ('G', 'Green'), ('C', 'Colorless'), ('M', 'Multicolor')], max_length=1, null=True),
        ),
    ]
