# Generated by Django 6.0 on 2026-02-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_card_type_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cmc',
            field=models.FloatField(default=0.0),
        ),
    ]
